export { KERNEL_VERSION } from './version.js'
export * from './ir/fact.js'
export * from './ir/types.js'
export * from './ir/query.js'
export * from './engine/rule-types.js'
export * from './engine/pack-loader.js'
export * from './engine/runner.js'
export * from './lock/types.js'
export * from './lock/derive.js'
export * from './lock/staleness.js'
export { resolveSurface } from './surface/resolve.js'
